language: d

d:
  - dmd #-2.070.1
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - dmd-2.065.0
  - gdc-4.9.2
  - ldc-0.14.0
  - ldc-0.15.1
  - ldc-0.16.0
  - ldc
  - ldc-1.0.0-alpha1
